ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Hive.Repo, :manual)

# Mimic-copy modules whose helpers we want to stub in tests so async: true
# tests don't have to mutate Application config. Stubs apply per-test
# (process-local), keeping parallelism safe.
Mimic.copy(Hive.Agents)
Mimic.copy(Hive.Agents.Sessions)
Mimic.copy(Hive.Drops.Agents.ReleaseDropItemAgent)
Mimic.copy(Hive.Drops.DomainClassification)
Mimic.copy(Hive.Domains.Evolution)
Mimic.copy(Hive.Forage.GitHubIssueClassification)
Mimic.copy(Hive.Forage.Agents.GitHubIssueClassifierAgent)
Mimic.copy(Hive.Specs)
Mimic.copy(Hive.Specs.Agents.RevisionSummaryAgent)
Mimic.copy(Hive.Specs.Agents.ReviewRequestAgent)
Mimic.copy(Hive.Specs.RevisionSummaries)
Mimic.copy(Hive.Auth)
Mimic.copy(Hive.GitHub.Client)
Mimic.copy(Hive.GitHub.Issues)
Mimic.copy(Hive.GitHub.Releases)
Mimic.copy(Hive.GitHub.Repositories)
Mimic.copy(Hive.GitHub.Webhooks)
Mimic.copy(Hive.Slack)
Mimic.copy(Hive.Slack.API)
Mimic.copy(Hive.Slack.Installations)
Mimic.copy(Hive.Slack.Signature)
Mimic.copy(HiveWeb.OpenGraph)
Mimic.copy(Boruta.Oauth)
Mimic.copy(Boruta.Openid)
Mimic.copy(Condukt, type_check: true)
Mimic.copy(Condukt.Session)
Mimic.copy(Condukt.Operation)
Mimic.copy(Req)
