defmodule Hive.Repo.Migrations.MigrateErrorsIssueIdsToDeterministic do
  @moduledoc """
  Rewrites every `errors_issues.id` (previously an autogenerated random
  UUID at insert time) to a UUIDv5 deterministically derived from
  `(project_id, fingerprint)`. This lets `Hive.Errors.record_event/2`
  compute the issue id in memory and skip the synchronous
  `INSERT ... ON CONFLICT DO UPDATE RETURNING id` round-trip that
  previously blocked every accepted envelope.

  The ClickHouse side (`errors_events.issue_id`) is migrated in
  lockstep so cross-store joins keep working. Both migrations run
  inline in the same task on `mix ecto.migrate`; failure of either
  leaves the deployment in an inconsistent state, so this migration
  should run against a small `errors_issues` table (Hive's self-
  monitor writes only, until an external project's Data Source Name
  starts producing envelopes).
  """
  use Ecto.Migration

  import Ecto.Query

  @uuid_namespace <<0x6F, 0x66, 0xEA, 0xF6, 0x2C, 0x18, 0x5C, 0x11, 0xA5, 0xB2, 0xD1, 0xF4, 0x5D,
                    0x8D, 0x22, 0x1A>>

  def up do
    repo = Hive.Repo

    %{rows: rows} =
      Ecto.Adapters.SQL.query!(repo, "SELECT id::text, project_id::text, fingerprint FROM errors_issues", [])

    Enum.each(rows, fn [old_id, project_id, fingerprint] ->
      new_id = deterministic_id(project_id, fingerprint)

      unless new_id == old_id do
        # Postgres: rewrite the issue row's primary key. No other
        # Postgres table references `errors_issues.id`, so this is
        # safe without cascading.
        Ecto.Adapters.SQL.query!(
          repo,
          "UPDATE errors_issues SET id = $1 WHERE id = $2",
          [Ecto.UUID.dump!(new_id), Ecto.UUID.dump!(old_id)]
        )

        # ClickHouse: rewrite every `errors_events` row that pointed
        # to the old id. Uses an ALTER TABLE ... UPDATE mutation,
        # which ClickHouse applies asynchronously in the background.
        alter_click_house_events(project_id, fingerprint, new_id)
      end
    end)
  end

  def down do
    # Irreversible: the original ids weren't stored anywhere.
    :ok
  end

  defp deterministic_id(project_id, fingerprint) do
    name = project_id <> ":" <> fingerprint

    <<time_low::32, time_mid::16, _::4, time_hi::12, _::2, clock_hi::14, node::48,
      _rest::binary>> = :crypto.hash(:sha, @uuid_namespace <> name)

    binary =
      <<time_low::32, time_mid::16, 5::4, time_hi::12, 2::2, clock_hi::14, node::48>>

    Ecto.UUID.cast!(binary)
  end

  defp alter_click_house_events(project_id, fingerprint, new_id) do
    with true <- Application.get_env(:hive, :clickhouse_enabled, false),
         {:ok, _pid} <- ensure_ingest_repo() do
      Ecto.Adapters.SQL.query!(
        Hive.IngestRepo,
        "ALTER TABLE errors_events UPDATE issue_id = {new_id:String} " <>
          "WHERE project_id = {project_id:String} AND fingerprint = {fingerprint:String}",
        %{"new_id" => new_id, "project_id" => project_id, "fingerprint" => fingerprint}
      )

      :ok
    else
      _ -> :ok
    end
  end

  # `mix ecto.migrate` starts Hive.Repo but not Hive.IngestRepo, so
  # ensure the ClickHouse repo is running before we issue mutations
  # against it. Ignore the "already started" case for idempotency
  # when the migration is co-run with the app supervisor.
  defp ensure_ingest_repo do
    case Hive.IngestRepo.start_link() do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, pid}} -> {:ok, pid}
      {:error, _} = err -> err
    end
  end
end
